version: "3.8"

services:
  app:
    image: project-management-server
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    env_file:
      - .env
    stdin_open: true
    tty: true
    volumes:
      - ".:/usr/src/app"