openapi: 3.0.0
info:
  title: Project Management API
  version: 1.0.0
  description: API documentation for the Project Management system

servers:
  - url: /api/v1

paths:
  /users/register:
    post:
      summary: Register a new user
      tags: [Users]
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - fullName
                - email
                - password
              properties:
                fullName:
                  type: object
                  properties:
                    firstName:
                      type: string
                      example: John
                    lastName:
                      type: string
                      example: Doe
                email:
                  type: string
                  example: john@example.com
                password:
                  type: string
                  example: mysecurepassword
      responses:
        201:
          description: User created successfully
        400:
          description: Invalid input
